portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('yeakub.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    #1
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),

    #Where can I find OR set theses paths these values
    #2
    path('password_reset_done/', 
        auth_views.PasswordResetDoneView.as_view(template_name="email_sent.html"),name="password_reset_done"),
    #3
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),

    #4
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_complete.html"), name="password_reset_complete"),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yeakub/urls.py
from django.urls import path

from django.conf import settings
from .import views
from django.conf.urls.static import static


urlpatterns = [
    path('',views.home,name='home'),
    path('posts/',views.posts,name='posts'),
    path('all_posts', views.all_posts, name='all_posts'),
    path('post/<slug:slug>/',views.post,name='post'),
    # path('post/<str:pk>/',views.post,name='post'),
    path('profile/',views.profile,name='profile'),
    path('skill/', views.skills, name='skill'),
    path('otherskill/', views.otherskills, name='otherskill'),
    

    # CRUD PATHS
    path('create_post/', views.createPost, name='create_post'),
    path('update_post/<slug:slug>/', views.updatePost, name='update_post'),
    path('delete_post/<slug:slug>/', views.deletePost, name='delete_post'),


    # Email

    path('send_email/', views.sendEmail,name='send_email'),


    path('login/', views.loginPage, name="login"),
	path('register/', views.registerPage, name="register"),
	path('logout/', views.logoutUser, name="logout"),

	path('account/', views.userAccount, name="account"),
	path('update_profile/', views.updateProfile, name="update_profile"),

]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yeakub/models.py
from time import timezone
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=200, blank=True, null=True)
	last_name = models.CharField(max_length=200, blank=True, null=True)
	email = models.CharField(max_length=200)
	profile_pic = models.ImageField(null=True, blank=True, upload_to="images", default="/user.png")
	bio = models.TextField(null=True, blank=True)
	twitter = models.CharField(max_length=200,null=True, blank=True)

	def __str__(self):
		name = str(self.first_name)
		if self.last_name:
			name += ' ' + str(self.last_name)
		return name


class Tag(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name
    


class Post(models.Model):
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True,upload_to="images", default="placeholder.png")
    body = RichTextUploadingField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, null=True)
    slug = models.SlugField(null=True, blank=True)
    project_link = models.CharField(max_length=300, null=True, blank=True)
    github_link = models.CharField(max_length=300, null=True, blank=True)
    def __str__(self):
        return self.headline
    
    def save(self, *args, **kwargs):
        if self.slug == None:
            slug = slugify(self.headline)
            has_slug = Post.objects.filter(slug = slug).exists()
            count = 0
            slug = slugify(self.headline) + '-' + str(count)
            has_slug = Post.objects.filter(slug=slug).exists()
            self.slug = slug
        super().save(*args, **kwargs)



class PostComment(models.Model):
	author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
	post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)
	body = models.TextField(null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

	def __str__(self):
		return self.body

	@property
	def created_dynamic(self):
		now = timezone.now()
		return now


class Skills(models.Model):
    skill_name = models.CharField(max_length=50, null=False, blank=False, unique=True)
    
    def __str__(self):
          return self.skill_name
      
      

class OtherSkill(models.Model):
    skill_name = models.CharField(max_length=50, null=False, blank=False, unique=True)
    
    def __str__(self):
          return self.skill_name

yeakub/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Post, Profile, Skills, OtherSkill

class CustomUserCreationForm(UserCreationForm):

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
    
        widgets = {
            'tags' : forms.CheckboxSelectMultiple(),
        }

class UserForm(ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email']
		

class ProfileForm(ModelForm):
	class Meta:
		model = Profile
		fields = '__all__'
		exclude = ['user']
  
class SkillsForm(ModelForm):
    class Meta:
        model = Skills
        fields = '__all__'
        
class OtherSkillsForm(ModelForm):
    class Meta:
        model = OtherSkill
        fields = '__all__'

yeakub/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .decorators import *

from .models import Post, PostComment, Skills, OtherSkill
from .forms import PostForm, CustomUserCreationForm, ProfileForm, UserForm, SkillsForm, OtherSkillsForm
from .filters import PostFilter

# Create your views here.


def home(request):
    posts = Post.objects.filter(active=True, featured=True)[0:3]
    my_data = Skills.objects.all()
    otherskill = OtherSkill.objects.all()
    context = {'posts': posts,'skills': my_data,'otherskill': otherskill}
    
    return render(request, 'base/index.html', context)


def posts(request):
    posts = Post.objects.filter(active=True)

    # Search or filter
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs

    # pagination
    page = request.GET.get('page')
    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    # posts = Post.objects.all()
    context = {'posts': posts, 'myFilter': myFilter}
    return render(request, 'base/posts.html', context)


def all_posts(request):
    return render(request, 'base/all_posts.html')


def post(request, slug):
    post = Post.objects.get(slug=slug)

    if request.method == 'POST':
        PostComment.objects.create(
            author=request.user.profile,
            post=post,
            body=request.POST['comment']
        )
        messages.success(request, "You're comment was successfuly posted!")

        return redirect('post', slug=post.slug)

    context = {'post': post}
    return render(request, 'base/post.html', context)


def profile(request):
    return render(request, 'base/profile.html')


# CRUD VIEWs

@login_required(login_url="home")
def createPost(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('account')

    context = {'form': form}
    return render(request, 'base/post_form.html', context)


@login_required(login_url="home")
def updatePost(request, slug):
    post = Post.objects.get(slug=slug)
# def updatePost(request, pk):
#     post = Post.objects.get(id=pk)
    form = PostForm(instance=post)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context = {'form': form}
    return render(request, 'base/post_form.html', context)


@login_required(login_url="home")
def deletePost(request, slug):
    post = Post.objects.get(slug=slug)

    if request.method == 'POST':
        post.delete()
        return redirect('posts')
    context = {'item': post}
    return render(request, 'base/delete.html', context)

    # Email


def sendEmail(request):
    if request.method == 'POST':
        template = render_to_string('base/email.html', {
            'name': request.POST['name'],
            'subject': request.POST['subject'],
            'email': request.POST['email'],
            'message': request.POST['message'],
        })
        email = EmailMessage(
            request.POST['subject'],
            template,
            settings.EMAIL_HOST_USER,
            ['yeakub161736@gmail.com']
        )
        email.fail_silently = False
        email.send()
    return render(request, 'base/email_sent.html')


# login information

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        # Little Hack to work around re-building the usermodel
        try:
            user = User.objects.get(email=email)
            user = authenticate(
                request, username=user.username, password=password)
        except:
            messages.error(request, 'User with this email does not exists')
            return redirect('login')

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Email OR password is incorrect')

    context = {}
    return render(request, 'base/login.html', context)


def registerPage(request):
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            messages.success(request, 'Account successfuly created!')

            user = authenticate(request, username=user.username,
                                password=request.POST['password1'])

            if user is not None:
                login(request, user)

            next_url = request.GET.get('next')
            if next_url == '' or next_url == None:
                next_url = 'home'
            return redirect(next_url)
        else:
            messages.error(request, 'An error has occured with registration')
    context = {'form': form}
    return render(request, 'base/register.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home')


@login_required(login_url="home")
def userAccount(request):
    profile = request.user.profile

    context = {'profile': profile}
    return render(request, 'base/account.html', context)


@login_required(login_url="home")
def updateProfile(request):
    user = request.user
    profile = user.profile
    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user)
        if user_form.is_valid():
            user_form.save()

        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('account')

    context = {'form': form}
    return render(request, 'base/profile_form.html', context)


# For Skills add

def skills(request):
    skill = SkillsForm()

    if request.method == 'POST':
        skill = SkillsForm(request.POST, request.FILES)
        if skill.is_valid():
            skill.save()
            messages.success(request, 'Successfuly add Skill!')
            return redirect('skill')
        else:
            messages.error(request, 'An error has occured with Add Skill')
    my_data = Skills.objects.all()
        
    context = {'skill': skill, 'skills': my_data}
    return render(request, 'base/add_skills.html', context)


# For Other Skills add
def otherskills(request):
    otherskill = OtherSkillsForm()

    if request.method == 'POST':
        otherskill = OtherSkillsForm(request.POST, request.FILES)
        if otherskill.is_valid():
            otherskill.save()
            messages.success(request, 'Successfuly add Skill!')
            return redirect('otherskill')
        else:
            messages.error(request, 'An error has occured with Add Skill')
    my_data = OtherSkill.objects.all()
        
    context = {'otherskill': otherskill, 'otherskills': my_data}
    return render(request, 'base/other_skill.html', context)

yeakub/templates/base/account.html
{% include 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style type="text/css">
    #div_id_tags, #id_tags{
        max-height: 100px;
        overflow-y: scroll;
        border-radius: 5px;
        padding: 5px;
    }

	#user_pic{
		height: 200px;
		width: 200px;
		border-radius: 50%;
		border:5px solid #888;
		margin:0 auto;
		object-fit: cover;
	}

	#user-info-box{
		text-align: center;
	}
	
</style>

<div class="main-container">
	<br>
	<div class="row">
		<div class="col-md-4">
			<div class="card card-body" id="user-info-box">
				<img id="user_pic" src="{{profile.profile_pic.url}}">
				<br>
				<h2>{{profile}}</h2>
				<p>Email: {{profile.email}}</p>
				<hr>
				<p>{{profile.bio}}</p>
				<hr>
				<a class="btn btn-info btn-block" href="{% url 'update_profile' %}">Edit Profile</a>
			</div>
		</div>
		<div class="col-md-8">
			<div class="card card-body">
				<div class="collection">
					
					<a class="btn btn-info btn-block" style="margin-bottom: 50px; margin-top: 20px;" href="{% url 'create_post' %}">Create Post</a>
					<hr>
					<a class="btn btn-info btn-block" style="margin-bottom: 50px; margin-top: 20px;" href="{% url 'posts' %}">See All Posts</a>
					<hr>
					<a class="btn btn-info btn-block" style="margin-bottom: 50px; margin-top: 20px;" href="{% url 'skill' %}">Add Skill</a>
					<br>
					<a class="btn btn-info btn-block" style="margin-bottom: 50px; margin-top: 20px;" href="{% url 'otherskill' %}">Add Other Skill</a>



				</div>
				<h3>My Orders:</h3>
				<hr>
				<table class="table">
					<thead class="thead-dark">
						
						<tr>
							<th>Transaction ID</th>
							<th>Date</th>
							<th>Items</th>
							<th>Total</th>
							<th></th>
						</tr>
						
					</thead>
					<tr>
						<td>122523462</td>
						<td>11-24-2020</td>
						<td>2</td>
						<td>$12.18</td>
						<td><a class="btn btn-dark btn-sm" href="">View Order</a></td>
					</tr>

					<tr>
						<td>122523123</td>
						<td>11-29-2020</td>
						<td>7</td>
						<td>$53.65</td>
						<td><a class="btn btn-dark btn-sm" href="">View Order</a></td>
					</tr>
				</table>				
			</div>
		</div>
	</div>
    
</div>

{% endblock content %}

yeakub/templates/base/delete.html
{% extends 'base/main.html' %}
{% load static %}

{% block content %}
<div class="main-container">

    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete {{item}}?</p>
        <input class="btn btn-danger"  type="submit" value="Confirm">
    </form>
</div>

{% endblock content %}

yeakub/templates/base/email.html
{{name}}
{{subject}}
{{email}}
{{message}}

yeakub/templates/base/email_sent copy.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}


<div class="main-container">
	<h3>Password reset sent</h3>

<div class="custom-container">
	<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

	<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

</div>

{% endblock content %}

yeakub/templates/base/email_sent.html
{% extends 'base/main.html' %}

{% block content %}

<style type="text/css">
    html,body{
        height: 100%;
    }

    #page-wrapper {
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        background-color: #eaeaea;
    }
    #success-box {
        max-width: 600px;
        height: auto;
        background-color: #fff;
        border: 1px solid #888;
        border-radius: 5px;
        padding: 15px;
        justify-content: center;
        align-items: center;
        text-align: center;
        margin-left: 400px;
        margin-top: 150px;
    }
    #success-box p{
        font-size: 18px;
    }
</style>
<div class="page-wrapper">
    <div id="success-box" class="content-block">
        <h1>Thanks for reachint out !</h1>
        <p>Your message was successfully sent. I will do my best to get back to you in a timely manner :)</p>
        <a id="back-btn" href="{% url 'home' %}">BACK TO HOME PAGE</a>
    </div>
</div>

{% endblock content %}

yeakub/templates/base/login.html
{% include 'base/main.html' %}
{% load static %}
{% block content %}
<style>
	#login-page-wrapper{
		background: #eaeaea;
		height: 100vh;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	#login-form-wrapper{
		width: 400px;
		background: #fff;
		padding: 20px;
		-webkit-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		-moz-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
	}

	@media screen and (max-width: 400px){
		#login-form-wrapper{
			width: 95%;
		}
	}
</style>

<section id="login-page-wrapper">
	<div id="login-form-wrapper">
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == 'success' %}
					<div class="alert alert-success" role="alert">
						<span>{{message}}</span>					
					</div>
				{% elif message.tags == 'error' %}
					<div class="alert alert-danger" role="alert">
						<span>{{message}}</span>					
					</div>
				{% endif %}
			{% endfor %}
		{% endif %}

		<h3 style="text-align: center">Member Login</h3>
		<hr>
		<form method="POST">
			{% csrf_token %}
			<label>Email</label>
			<input class="form-control" type="email" name="email">
			<br>
			<label>Password</label>
			<input class="form-control" type="password" name="password">
			<br>
			<input class="btn btn-primary btn-lg btn-block" type="submit" value="Login">
		</form>

		<br>
		<p>Dont have an account? <a href="{% url 'register' %}">Register</a></p>
		<p>Forgot your password? <a href="{% url 'password_reset' %}">Reset</a></p>
	</div>
</section>

{% endblock content %}

yeakub/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap"
            rel="stylesheet">
            <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
        <!-- == color Style css==== -->
        <link id="theme-style" rel="stylesheet" type="text/css" href="">
        
        <title>Document</title>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-47692315-56');
        </script>
    </head>
    
<body>
    {% include 'base/navbar.html' %}
    <hr>


    {% block content %}
    {% comment %} content start here {% endcomment %}
    {% endblock content %}
</body>
</html>

yeakub/templates/base/navbar.html
<!DOCTYPE html>
{% load static %}

    
<div class="nav-wrapper">

    <a href="{% url 'home' %}">
        <div class="dots-wrapper">
       
            <div class="browser-dot" id="dot-1"></div>
            <div class="browser-dot" id="dot-2"></div>
            <div class="browser-dot" id="dot-3"></div>
        </div>
    </a>
   
    <div class="navigation">
        <li><a href="{% url 'home' %}#contact">Contact</a></li>
		{% if request.user.is_authenticated %}
			<li><a href="{% url 'account' %}"> Account</a></li>
			<li><a href="{% url 'logout' %}">Logout</a></li>
		{% else %}
			<li><a href="{% url 'login' %}">Login</a></li>
		{% endif %}
    </div>
</div>

<script type="text/javascript">
	let menu = 'closed' 

	let menuIcon = document.getElementById('menu-icon')
	let navigation = document.getElementById('navigation')
	let closeBtn = document.getElementById('close-btn')

	menuIcon.addEventListener('click', toggleMenu)
	closeBtn.addEventListener('click', toggleMenu)


	function toggleMenu(){
		if (menu == 'closed'){
			navigation.style.display = 'block'
			closeBtn.style.display = 'block'
			menu = 'open'
		}else{
			navigation.style.display = 'none'
			closeBtn.style.display = 'none'
			menu = 'closed'
		}
	}

	    
	// Attaching the event listener function to window's resize event
	
	window.addEventListener("resize", function(){
		let width = document.documentElement.clientWidth;
		if(width > 1080){
				navigation.style.display = 'block'
		}else{
				navigation.style.display = 'none'
		}
		menu = 'closed'
		closeBtn.style.display = 'none'
	});
	
</script>

yeakub/templates/base/other_skill.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<html>
    <head>
        <title>Create Post</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
    <style>
        h2{
            text-align: center;
            margin-bottom: 25px;
        }
        #form{
            display: grid;
            max-height: 450px;
        }
        #id_skill_name{
            height: 200px;
            text-align: justify;
        }
        .skill-ul{
            height: 100%;
            background-color: antiquewhite;
            align-items: center;
            margin-bottom: 40px;
        }
        .skill p {
            background-color: aqua;
            font-size: 1.25em;
        }
        .skill{
            text-align: center;
            align-items: center;
            
        }
       
        
    </style>
    </head>
<body>
    


    <div class="main-container">
        {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div class="alert alert-success" role="alert">
                            <span>{{message}}</span>					
                        </div>
                    
                    {% elif message.tags == 'error' %}
                        <div class="alert alert-danger" role="alert">
                            <span>{{message}}</span>					
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        <h2>Other Skill Form</h2>
        <form class="create_btn" id="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{otherskill.skill_name}}
            
            <input style="margin-bottom: 90px;" class="btn btn-primary" id="btn_st" type="submit" value="Submit Post">
        </form>

        

    </div>
    <div>
        <ul class="skill-ul">
            <li class="skill"><p>All Skills</p></li>
            {% for skill in otherskills %}
            <li class="skill">{{skill.skill_name}}</li>
            {% empty %}
            <li class="skill">No data found</li>
            {% endfor %}
            
        </ul>
    </div>

</body>
</html>
{% endblock content %}

yeakub/templates/base/password_reset copy.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<div class="main-container">
	<h3>Password reset</h3>

	<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>


	<form method="POST" action="">
		{% csrf_token %}
		{{form|crispy}}
		<br>
		<input class="btn btn-primary" type="submit" value="Reset my password">
	</form>
</div>

{% endblock content %}

yeakub/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style type="text/css">
    #div_id_tags, #id_tags{
        max-height: 100px;
        overflow-y: scroll;
        border-radius: 5px;
        padding: 5px;
    }
</style>
<div class="main-container">
    <h2>Posts</h2>
    <form id="searchForm" method="GET">
        {{myFilter.form|crispy}}
        <input class="btn btn-primary" type="submit" value="search">
    </form>


    <div class="post-wrapper">
        {% for post in posts%}
        <div>
            <div class="post">
                <img src="{{post.thumbnail.url}}" class="thumbnail" alt="">
                <div class="post-preview">
                    <h6 class="post-title">{{post.headline}}</h6>
                    <p class="post-intro">{{post.sub_headline}}</p>
                    <a href="{% url 'post' post.slug %}">Read More</a>

                    {% if request.user.is_authenticated %}
                        <a href="{% url 'update_post' post.slug %}">| Edit</a>
                        <a href="{% url 'delete_post' post.slug %}">| Delete</a>
                    {% endif %}

                    <hr>
                    {% for tag in post.tags.all %} 
                         <span class="tag" style="display: inline-block;
                         color: #fff;
                         background-color: #888;
                         border-radius: 5px;
                         margin: 2px;
                         padding: 2px 5px;
                         font-size: 12px;">{{tag}}</span>
                    {% endfor %}

                    <hr>
                    <div class="link_btn"> <a href="{{post.github_link}}" class="btn btn-primary" id="btn_left">Live preview</a><a href="{{post.project_link}}" class="btn btn-primary" id="btn_right">Code Preview</a></div>
                </div>
            </div>
        </div>
        {% empty %}
            <h3>No Post found...</h3>
        {% endfor %}
    </div>
   
    <div class="row">
        {% if posts.has_other_pages %}
            <ul class="pagination">
                           <!-- ======= Previous Page======-->
                {% if posts.has_previous %}
                    <li class="page-item"><a data-page="?page={{posts.previous_page_number}}"   href="?page={{posts.previous_page_number}}" class="page-link">&laquo;</a></li>
                    
                    <li class="page-item"><a data-page="?page=1" href="?page=1" class="page-link">First</a></li>
                {% endif %}
                      
                <!-- ====== page number=====-->
                {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                        <li class="page-item"><a class="active page-link">{{i}}</a></li>
                    {% else %}
                        <li class="page-item"><a data-page="?page={{i}}" class="page-link" href="?page={{i}}" class="page-link">{{i}}</a></li>
                    {% endif %}
                {% endfor %}
                       <!--  ======== next page number======-->
                {% if posts.has_next %}
                    <li class="page-item"><a data-page="?page={{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>
                    
                    <li class="page-item"><a data-page="?page={{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo;</a></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
   
</div>




<script type="text/javascript">
    let searchForm = document.getElementById('searchForm')
    let pageLink = document.getElementById('page-link')

    for(var i=0; pageLink.length; i++){

        pageLink[i].addEventListener('click',function(e){
            e.preventDefault()
            let page = this.dataset.page
            console.log('page', page)
            searchForm.innerHTML += '<input value="${page}" name="page">'
        })
    }
</script>
{% endblock content %}

yeakub/templates/base/profile_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="main-container">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input class="btn btn-primary" type="submit" value="Save">
	</form>
</div>
{% endblock content %}